# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Smart Electrical GB
email: info@smartelectricalgb.co.uk
description: > #
  Smart electric description goes here.
baseurl: "/smart-electrical-gb" # the subpath of your site, e.g. /blog
url: "http://smartelectricalgb.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
